name: pump-failure-using-automl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - tpot
  - ipykernel
  - pandas
  - eli5
  - category_encoders
  - tqdm
  - h2o
  - scikit-learn=1.2.2
